version: '3.8'
services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    command: --deterministic --port 8545
    ports:
      - "8545:8545"

  python-app:
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      - WEB3_PROVIDER_URL=http://ganache:8545
    depends_on:
      - ganache
